### ISSUE TITLE
openlogin.esm.js getHashQueryParams 

### ISSUE THREAD

**Issue by suwu150** [Web3Auth/Auth#341]
node_modules/@toruslabs/openlogin/dist/openlogin.esm.js

```
   const params = getHashQueryParams(this.options.replaceUrlOnRedirect);
....
    if (params.error) {
      this.dappState = params.state;

      throw LoginError.loginFailed(params.error);
    }

```
When my access domain name address is `http://localhost:8081/welcome?error=access_denied&error_description=hhhhhhhh` , it will also throw an exception. This is unreasonable because these are basically two different businesses.

**Comment by chaitanyapotti** [comment]
typically oauth errors include error and error_description as query params when there's an error. that's why our sdk processes this when login is called. 
if you believe that those values are used for your business, you can clear those query params first and call our sdk then
